services:
  web:
    image: ghcr.io/artkingdom/nutchapol-web-profile:latest
    container_name: nutchapol-web-profile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      N8N_WEBHOOK_URL: "https://n8n.artnutchapol.me/webhook/portfolio-chat"
    restart: unless-stopped
